<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>PodoBot</AssemblyName>
    <RootNamespace>PodoBot</RootNamespace>
    <ApplicationIcon>Assets\PodoBot.ico</ApplicationIcon>
    <Version>0.3.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SocketIOClient" Version="4.0.5" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="8.0.0" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\PodoBot.ico" />
  </ItemGroup>
</Project>
